### ISSUE TITLE
Support takeScreenshot (missing function) in UiDeviceSnippet.java

### ISSUE THREAD

**Issue by VanilaMao** [google/snippet-uiautomator#44]
most functions are exposed as RPC from uiautomator uidevice, but some functions like takeScreenshot etc is missing from UiDeviceSnippet.java. We may fork one to add it, but it is nice if the repo can add it. If any one can create a PR to fix it, that would be appreciated

**Comment by ko1in1u** [comment]
Mobly support taking screenshot in [mobly.controllers.android_device.AndroidDevice.take_screenshot](https://mobly.readthedocs.io/en/stable/mobly.controllers.html#mobly.controllers.android_device.AndroidDevice.take_screenshot), so implementing this API is not in the plan.
